version: "3"

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  ios: ./build/ios/Taskfile.yml
  android: ./build/android/Taskfile.yml

vars:
  APP_NAME: "nekkus-net"
  BIN_DIR: "bin"
  VITE_PORT: "{{.VITE_PORT | default 9245}}"

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  build:go:
    summary: Builds only the Go binary (./cmd), no frontend. Use to verify code compiles.
    cmds:
      - go build -o "{{.BIN_DIR}}/{{.APP_NAME}}{{.exeExt}}" ./cmd
    vars:
      exeExt: '{{if eq OS "windows"}}.exe{{end}}'

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - task: common:run:server

  setup:docker:
    summary: Builds Docker image for cross-compilation (~800MB download)
    cmds:
      - task: common:setup:docker

  build:server:
    summary: Builds the application in server mode (no GUI, HTTP server only)
    cmds:
      - task: common:build:server

  run:server:
    summary: Runs the application in server mode
    cmds:
      - task: common:run:server

  build:docker:
    summary: Builds a Docker image for server mode deployment
    cmds:
      - task: common:build:docker

  run:docker:
    summary: Builds and runs the Docker image
    cmds:
      - task: common:run:docker
